-- =============================================================================
-- Migration 022 — Trip Short Codes for SEO-Friendly Slugs
-- =============================================================================
-- Adds a 6-character `short_code` column to the trips table. Used by the
-- frontend to build human-readable slug URLs:
--
--   /trip/qasra-kafr-al-laymun-may13-aB3xK9
--             └────city pair────┘ └date┘ └code┘
--
-- The full UUID URL keeps working — the React app handles either form,
-- looks up the trip by short_code, and 301-redirects UUID → slug as
-- the canonical form. This migration is the database half.
--
-- Why a separate column instead of slug-based lookup
-- ──────────────────────────────────────────────────
-- 1. Cities can change spelling, dates can shift (recurring trips edited
--    by the driver). The CODE is stable; the city/date prefix is
--    decoration. We always look up by short_code.
--
-- 2. Indexed lookups: short_code is 6 chars, deterministic, b-tree-indexed.
--    No need for a slug column with full-text concerns.
--
-- 3. Collisions: short_code is unique. A city+date prefix can repeat (5
--    drivers running the same route on the same day) and that's fine.
--
-- Code generation
-- ───────────────
-- We use a Crockford base32 alphabet (no 0/O/I/L confusion) of length 6:
--   32^6 = ~1 billion combinations. At 100 trips/day that's >27,000 years
--   of headroom before serious birthday-paradox collision risk.
--
-- Generated by trigger on INSERT — not application code — so:
--   • New trips always get a code (no "forgot to set it" bug)
--   • Manual SQL inserts also get codes (data fixture safety)
--   • Application doesn't need to retry-on-collision (DB does)
--
-- Idempotent: ADD COLUMN IF NOT EXISTS, CREATE OR REPLACE FUNCTION,
-- DROP TRIGGER IF EXISTS + CREATE TRIGGER. Safe to re-run.
-- =============================================================================

BEGIN;

-- ─────────────────────────────────────────────────────────────────────
-- SECTION 1 — Add column + index + uniqueness
-- ─────────────────────────────────────────────────────────────────────
-- Nullable initially so existing rows can be backfilled below before
-- we add the NOT NULL + UNIQUE constraints.

ALTER TABLE public.trips
  ADD COLUMN IF NOT EXISTS short_code TEXT;

COMMENT ON COLUMN public.trips.short_code IS
  '6-character Crockford base32 unique short identifier used in human-
   readable slug URLs (/trip/{cities}-{date}-{short_code}). Auto-
   generated by trg_trips_short_code on INSERT. Stable for the
   lifetime of the trip — never re-rolled even if cities/date change.';

-- ─────────────────────────────────────────────────────────────────────
-- SECTION 2 — Code generator (Crockford base32, 6 chars)
-- ─────────────────────────────────────────────────────────────────────
-- Crockford base32 uses 0-9 + A-Z minus I, L, O, U (visual confusion +
-- profanity-prevention). Plus we use the lowercase variant a-z minus
-- the same letters to widen the alphabet for shorter codes.
--
-- Why not pgcrypto's gen_random_bytes + base64? Because base64 has +/=
-- which are awful in URLs (need URL-encoding) and ambiguous casing
-- between systems. Crockford is URL-safe by construction.

CREATE OR REPLACE FUNCTION public.generate_trip_short_code()
RETURNS TEXT
LANGUAGE plpgsql VOLATILE
AS $$
DECLARE
  -- Mix of digits and unambiguous letters. 30 chars, length 6 → 30^6 ≈ 729M.
  alphabet TEXT := '23456789abcdefghjkmnpqrstuvwxyz';
  result   TEXT := '';
  i        INT;
BEGIN
  FOR i IN 1..6 LOOP
    result := result || substr(alphabet, 1 + floor(random() * length(alphabet))::int, 1);
  END LOOP;
  RETURN result;
END;
$$;

COMMENT ON FUNCTION public.generate_trip_short_code() IS
  'Returns a 6-character Crockford-style base32 short code for trip URLs.
   Excludes 0/1/i/l/o (visual confusion) and u (profanity prevention).
   Does NOT check uniqueness — caller (trigger) retries on collision.';

-- ─────────────────────────────────────────────────────────────────────
-- SECTION 3 — Trigger: assign short_code on insert
-- ─────────────────────────────────────────────────────────────────────
-- BEFORE INSERT so the row gets the code in its INSERT statement (no
-- second UPDATE round-trip). Retry up to 5x on collision — at 729M
-- code space and our trip volume this should never fire.

CREATE OR REPLACE FUNCTION public.trips_assign_short_code()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  v_attempt INT := 0;
  v_code    TEXT;
BEGIN
  -- Skip if explicitly set (data migration, restore, manual fixture)
  IF NEW.short_code IS NOT NULL THEN
    RETURN NEW;
  END IF;

  LOOP
    v_attempt := v_attempt + 1;
    v_code := public.generate_trip_short_code();

    -- Check for collision against existing codes
    IF NOT EXISTS (SELECT 1 FROM public.trips WHERE short_code = v_code) THEN
      NEW.short_code := v_code;
      RETURN NEW;
    END IF;

    IF v_attempt >= 5 THEN
      RAISE EXCEPTION 'Failed to generate unique trip short_code after 5 attempts';
    END IF;
  END LOOP;
END;
$$;

DROP TRIGGER IF EXISTS trg_trips_short_code ON public.trips;
CREATE TRIGGER trg_trips_short_code
  BEFORE INSERT ON public.trips
  FOR EACH ROW
  EXECUTE FUNCTION public.trips_assign_short_code();

-- ─────────────────────────────────────────────────────────────────────
-- SECTION 4 — Backfill existing rows
-- ─────────────────────────────────────────────────────────────────────
-- Loop over trips with NULL short_code and assign one each. Done in a
-- DO block (not a single UPDATE … SELECT) because each row needs an
-- independent random call AND a uniqueness check against codes already
-- assigned in this same backfill.

DO $$
DECLARE
  v_id   UUID;
  v_code TEXT;
  v_attempt INT;
BEGIN
  FOR v_id IN SELECT id FROM public.trips WHERE short_code IS NULL LOOP
    v_attempt := 0;
    LOOP
      v_attempt := v_attempt + 1;
      v_code := public.generate_trip_short_code();
      IF NOT EXISTS (SELECT 1 FROM public.trips WHERE short_code = v_code) THEN
        UPDATE public.trips SET short_code = v_code WHERE id = v_id;
        EXIT;
      END IF;
      IF v_attempt >= 5 THEN
        RAISE EXCEPTION 'Backfill failed: cannot generate unique short_code for trip %', v_id;
      END IF;
    END LOOP;
  END LOOP;
END $$;

-- ─────────────────────────────────────────────────────────────────────
-- SECTION 5 — Constraints + index
-- ─────────────────────────────────────────────────────────────────────
-- NOT NULL only after backfill. UNIQUE needs an index (Postgres creates
-- one implicitly for unique constraint, no separate CREATE INDEX needed).

ALTER TABLE public.trips
  ALTER COLUMN short_code SET NOT NULL;

-- Conditional unique constraint creation (idempotent re-run safety)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'trips_short_code_key'
       AND conrelid = 'public.trips'::regclass
  ) THEN
    ALTER TABLE public.trips
      ADD CONSTRAINT trips_short_code_key UNIQUE (short_code);
  END IF;
END $$;

COMMIT;
