-- ════════════════════════════════════════════════════════════════════════
-- Migration 062 — Capture + install prevent_driver_trip_conflict trigger
-- ════════════════════════════════════════════════════════════════════════
--
-- COMPLEMENT to migration 044 (prevent_passenger_booking_conflict).
--
-- BACKGROUND
-- The codebase referenced a `check_driver_trip_conflict` function in
-- migration 029's search-path-pinning list, but the function itself
-- was never captured in any migration. Worse: there's no evidence in
-- the migrations folder OR the seed scripts that a corresponding
-- TRIGGER was ever installed to call it.
--
-- The booking side has a robust contract:
--   migration 044 → check_passenger_booking_conflict()
--                → trigger prevent_passenger_booking_conflict
--                → blocks a passenger from booking two overlapping trips
--
-- The publishing side had no equivalent. A driver could:
--   - Post "Ramallah → Jenin, Tuesday 9am"
--   - Then immediately post "Hebron → Nablus, Tuesday 2pm"
--   - Then "Bethlehem → Tulkarm, Tuesday 11am"
-- All three on the same day, with seats available to book. Passengers
-- on different trips ended up booking a driver who can't physically
-- fulfill the schedule, and only discovered the conflict when the
-- driver no-showed.
--
-- WHAT THIS MIGRATION INSTALLS
--
-- (1) Function check_driver_trip_conflict — fires on INSERT to trips.
--     Looks for another active trip (status IN 'confirmed' or
--     'in_progress', NOT cancelled/completed/expired) by the same
--     driver_email on the same date. If found, RAISE EXCEPTION.
--     Same-calendar-day is the conservative rule we already use for
--     passengers (see migration 044's rationale): Mishwaro doesn't
--     store exact trip end-times, so any two same-day trips are
--     treated as a potential conflict.
--
-- (2) Trigger prevent_driver_trip_conflict — BEFORE INSERT on
--     public.trips, FOR EACH ROW, executes the function.
--
-- ADMIN BYPASS
-- Mirrors migration 044's contract: admins editing trips on behalf of
-- a driver skip the check. Implemented via auth_user_role().
--
-- WHY BEFORE INSERT NOT AFTER
-- BEFORE INSERT runs before the row is written, so the EXCEPTION
-- aborts the transaction cleanly with no trip row to clean up.
-- AFTER INSERT would write then throw, requiring a CASCADE delete.
--
-- IDEMPOTENCY
-- CREATE OR REPLACE for the function; DROP / CREATE for the trigger.
-- Safe to re-run.
--
-- ════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION public.check_driver_trip_conflict()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog, auth
AS $$
DECLARE
  v_caller_role    TEXT := public.auth_user_role();
  v_conflict_count INTEGER;
BEGIN
  -- Admin override — same contract as the booking-side trigger.
  -- Admins managing trips on behalf of a driver (rare but needed for
  -- support tickets and seed data) must be able to insert without
  -- this guard.
  IF v_caller_role = 'admin' THEN
    RETURN NEW;
  END IF;

  -- Only check on actual trip creation. Trip updates that change date
  -- are handled separately by change_trip_time (which enforces a
  -- ≤60-min delta) and should not trip this guard. UPDATEs that
  -- change driver_email aren't a real flow — that column is set at
  -- INSERT and held constant by guard_trip_updates.
  IF TG_OP <> 'INSERT' THEN
    RETURN NEW;
  END IF;

  -- Same-calendar-day check. Active means CONFIRMED or IN_PROGRESS.
  -- We exclude:
  --   - cancelled  → driver pulled the trip, no longer their commitment
  --   - completed  → past, doesn't conflict with future trips on same date
  --   - expired    → auto-expired by cron (migration 012's expire_stale_trips)
  -- Self-row exclusion via id <> NEW.id is defensive — at BEFORE INSERT
  -- NEW.id has been generated by the column default (uuid_generate_v4)
  -- but the row isn't visible to the SELECT yet, so this would be
  -- redundant if not for re-entry scenarios.
  SELECT COUNT(*)
  INTO v_conflict_count
  FROM public.trips
  WHERE driver_email = NEW.driver_email
    AND status IN ('confirmed', 'in_progress')
    AND id <> NEW.id
    AND date = NEW.date;

  IF v_conflict_count > 0 THEN
    RAISE EXCEPTION 'trip conflict — driver already has an active trip on %', NEW.date
      USING ERRCODE = '42501',
            HINT = 'You already have a trip published for that date. Cancel it first or pick another day.';
  END IF;

  RETURN NEW;
END $$;

REVOKE ALL ON FUNCTION public.check_driver_trip_conflict() FROM PUBLIC;
-- Trigger functions don't need direct EXECUTE grants — they run as
-- SECURITY DEFINER under the table owner's privileges. The function
-- only needs to exist; PostgreSQL invokes it on each trigger fire.

DROP TRIGGER IF EXISTS prevent_driver_trip_conflict ON public.trips;
CREATE TRIGGER prevent_driver_trip_conflict
  BEFORE INSERT ON public.trips
  FOR EACH ROW
  EXECUTE FUNCTION public.check_driver_trip_conflict();

-- ─── Verification ───────────────────────────────────────────────────
DO $$
DECLARE
  v_trigger_ok BOOLEAN;
  v_func_ok    BOOLEAN;
BEGIN
  SELECT EXISTS (
    SELECT 1 FROM pg_trigger
    WHERE tgname = 'prevent_driver_trip_conflict'
      AND NOT tgisinternal
  ) INTO v_trigger_ok;

  SELECT EXISTS (
    SELECT 1 FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public'
      AND p.proname = 'check_driver_trip_conflict'
  ) INTO v_func_ok;

  IF NOT v_trigger_ok THEN
    RAISE EXCEPTION 'MIGRATION 062 FAILED: trigger not installed';
  END IF;
  IF NOT v_func_ok THEN
    RAISE EXCEPTION 'MIGRATION 062 FAILED: function not installed';
  END IF;

  RAISE NOTICE 'MIGRATION 062 OK — prevent_driver_trip_conflict installed';
END $$;
