import React, { useState, useMemo } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useNavigate } from "react-router-dom";
import { Repeat, Plus, Trash2, Calendar, Clock, MapPin, DollarSign, Users, X as XIcon, Loader2, AlertCircle, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";
import { useAuth } from "@/lib/AuthContext";
import { supabase } from "@/lib/supabase";
import { useSEO } from "@/hooks/useSEO";
import { friendlyError } from "@/lib/errors";
import CityAutocomplete from "@/components/shared/CityAutocomplete";
import EmptyState from "@/components/shared/EmptyState";

const PATTERN_LABELS = {
  daily:     { label: "يومياً",        hint: "كل يوم" },
  weekdays:  { label: "أيام العمل",   hint: "الأحد - الخميس" },
  weekends:  { label: "العطلة",       hint: "الجمعة - السبت" },
  weekly:    { label: "أسبوعياً",     hint: "نفس اليوم كل أسبوع" },
};

/**
 * RecurringTrips — driver management page for recurring trip templates.
 *
 * URL: /recurring-trips
 *
 * Lets a driver:
 *   - See all their active recurring templates
 *   - Create a new template (open modal with pattern picker)
 *   - Delete a template (with confirm — future generated instances stay)
 *   - See how many instances were auto-generated per template
 *
 * NOT in v1:
 *   - Edit pattern (delete + recreate)
 *   - Pause/resume (delete + recreate)
 *   - Preview upcoming dates
 *
 * Templates are stored in `trips` table with is_template=TRUE. Instances
 * (auto-generated by the daily cron job — mig 081) have
 * parent_template_id pointing to the template. The cron job creates
 * up to 14 days of instances ahead.
 */
export default function RecurringTrips() {
  useSEO({ title: "الرحلات المتكررة", description: "إدارة قوالب الرحلات المتكررة" });
  const { user } = useAuth();
  const navigate = useNavigate();
  const qc = useQueryClient();

  const [showForm, setShowForm] = useState(false);
  const [deleteTarget, setDeleteTarget] = useState(null);

  // Templates owned by current driver
  const { data: templates = [], isLoading } = useQuery({
    queryKey: ["recurring-templates", user?.email],
    queryFn: async () => {
      if (!user?.email) return [];
      const { data, error } = await supabase
        .from("trips")
        .select("id, from_city, to_city, date, time, price, available_seats, recurrence_pattern, recurrence_until, status, created_at, car_model, car_color, notes")
        .eq("driver_email", user.email)
        .eq("is_template", true)
        .order("created_at", { ascending: false });
      if (error) throw error;
      return data || [];
    },
    enabled: !!user?.email,
  });

  // Instance counts per template (so the driver can see "12 instances
  // generated" at a glance). Single batch query rather than one per
  // template — avoids N+1 round-trips.
  const { data: instanceCounts = {} } = useQuery({
    queryKey: ["recurring-instance-counts", user?.email, templates.map(t => t.id).join(",")],
    queryFn: async () => {
      if (templates.length === 0) return {};
      const today = new Date().toISOString().slice(0, 10);
      const { data, error } = await supabase
        .from("trips")
        .select("parent_template_id")
        .in("parent_template_id", templates.map(t => t.id))
        .gte("date", today);
      if (error) throw error;
      // Tally
      const counts = {};
      for (const row of data || []) {
        counts[row.parent_template_id] = (counts[row.parent_template_id] || 0) + 1;
      }
      return counts;
    },
    enabled: templates.length > 0,
  });

  // Delete template mutation
  const deleteMutation = useMutation({
    mutationFn: async (templateId) => {
      const { error } = await supabase
        .from("trips")
        .delete()
        .eq("id", templateId)
        .eq("is_template", true);
      if (error) throw error;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["recurring-templates"] });
      qc.invalidateQueries({ queryKey: ["my-trips"] });
      toast.success("تم حذف القالب. الرحلات المنشورة مسبقاً لا تزال متاحة.");
      setDeleteTarget(null);
    },
    onError: (err) => {
      toast.error(friendlyError(err, "تعذر حذف القالب"));
    },
  });

  // Only drivers see this page meaningfully. Non-drivers / unverified
  // users see a hint to apply as driver.
  if (!user) {
    return (
      <div className="max-w-2xl mx-auto px-4 py-12 text-center">
        <Repeat className="w-12 h-12 text-muted-foreground/30 mx-auto mb-3" />
        <p className="font-medium mb-2">سجّل الدخول لإدارة الرحلات المتكررة</p>
        <Button onClick={() => navigate("/login")}>تسجيل الدخول</Button>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 py-8">
      {/* Header */}
      <div className="flex flex-wrap items-start justify-between gap-3 mb-6">
        <div>
          <h1 className="text-2xl font-bold text-foreground flex items-center gap-2">
            <Repeat className="w-6 h-6 text-primary" aria-hidden="true" />
            الرحلات المتكررة
          </h1>
          <p className="text-sm text-muted-foreground mt-0.5">
            عرّف قالباً واحداً، وسننشر الرحلات تلقائياً كل يوم
          </p>
        </div>
        {!showForm && (
          <Button
            onClick={() => setShowForm(true)}
            className="bg-primary text-primary-foreground gap-2 min-h-[44px] rounded-xl"
          >
            <Plus className="w-4 h-4" aria-hidden="true" />
            قالب جديد
          </Button>
        )}
      </div>

      {/* Info card */}
      <div className="bg-primary/5 border border-primary/20 rounded-2xl p-4 mb-6 flex items-start gap-3">
        <Sparkles className="w-5 h-5 text-primary shrink-0 mt-0.5" aria-hidden="true" />
        <div className="text-sm text-foreground/90 leading-relaxed">
          <p className="font-medium mb-1">كيف تعمل الرحلات المتكررة؟</p>
          <p className="text-xs text-muted-foreground">
            عرّف القالب مرة واحدة (المدينتان، الوقت، السعر، المقاعد، النمط).
            كل يوم في الساعة 03:00 صباحاً، نُنشئ رحلات للأسبوعين القادمين تلقائياً.
            يمكن للركاب رؤيتها وحجزها كأي رحلة عادية. لإيقاف التوليد، احذف القالب.
          </p>
        </div>
      </div>

      {/* Create form */}
      {showForm && (
        <NewTemplateForm
          onCancel={() => setShowForm(false)}
          onCreated={() => {
            setShowForm(false);
            qc.invalidateQueries({ queryKey: ["recurring-templates"] });
            qc.invalidateQueries({ queryKey: ["my-trips"] });
            toast.success("تم إنشاء القالب وتوليد رحلات الأسبوعين القادمين ✓");
          }}
        />
      )}

      {/* Templates list */}
      {isLoading ? (
        <div className="flex items-center justify-center py-12">
          <Loader2 className="w-6 h-6 text-muted-foreground animate-spin" />
        </div>
      ) : templates.length === 0 && !showForm ? (
        <EmptyState
          icon={<Repeat className="w-12 h-12" />}
          title="لا توجد قوالب متكررة بعد"
          description="أنشئ قالباً للرحلة التي تكررها يومياً أو أسبوعياً"
          action={
            <Button onClick={() => setShowForm(true)} className="gap-2 min-h-[44px]">
              <Plus className="w-4 h-4" />
              قالب جديد
            </Button>
          }
        />
      ) : (
        <div className="space-y-3">
          {templates.map((t) => {
            const count = instanceCounts[t.id] || 0;
            const patternMeta = PATTERN_LABELS[t.recurrence_pattern] || { label: t.recurrence_pattern, hint: "" };
            return (
              <div key={t.id} className="bg-card rounded-2xl border border-border p-4 sm:p-5">
                <div className="flex items-start justify-between gap-3 mb-3">
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1">
                      <MapPin className="w-4 h-4 text-primary shrink-0" aria-hidden="true" />
                      <span className="font-bold text-foreground truncate">
                        {t.from_city} ← {t.to_city}
                      </span>
                    </div>
                    <div className="flex flex-wrap items-center gap-2 mt-2 text-xs">
                      <span className="inline-flex items-center gap-1 bg-primary/10 text-primary px-2 py-1 rounded-full">
                        <Repeat className="w-3 h-3" aria-hidden="true" />
                        {patternMeta.label}
                      </span>
                      <span className="inline-flex items-center gap-1 bg-muted text-foreground px-2 py-1 rounded-full">
                        <Clock className="w-3 h-3" aria-hidden="true" />
                        {t.time}
                      </span>
                      <span className="inline-flex items-center gap-1 bg-emerald-500/10 text-emerald-700 px-2 py-1 rounded-full">
                        <DollarSign className="w-3 h-3" aria-hidden="true" />
                        ₪{t.price}
                      </span>
                      <span className="inline-flex items-center gap-1 bg-muted text-foreground px-2 py-1 rounded-full">
                        <Users className="w-3 h-3" aria-hidden="true" />
                        {t.available_seats}
                      </span>
                      {t.recurrence_until && (
                        <span className="inline-flex items-center gap-1 bg-amber-500/10 text-amber-700 px-2 py-1 rounded-full">
                          <Calendar className="w-3 h-3" aria-hidden="true" />
                          حتى {t.recurrence_until}
                        </span>
                      )}
                    </div>
                  </div>
                  <button
                    onClick={() => setDeleteTarget(t)}
                    className="shrink-0 inline-flex items-center justify-center w-11 h-11 rounded-xl text-muted-foreground hover:text-destructive hover:bg-destructive/10 active:bg-destructive/20 transition-colors"
                    aria-label="حذف القالب"
                    title="حذف"
                  >
                    <Trash2 className="w-4 h-4" />
                  </button>
                </div>
                <div className="flex items-center justify-between text-xs text-muted-foreground pt-3 border-t border-border">
                  <span>{patternMeta.hint}</span>
                  <span>
                    {count > 0
                      ? `${count} رحلة منشورة قادمة`
                      : "لا رحلات قادمة بعد — انتظر التوليد الليلي"}
                  </span>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Delete confirmation modal */}
      {deleteTarget && (
        <div
          className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4"
          onClick={() => !deleteMutation.isPending && setDeleteTarget(null)}
        >
          <div
            role="alertdialog"
            aria-modal="true"
            className="bg-card rounded-2xl max-w-sm w-full p-6"
            onClick={(e) => e.stopPropagation()}
            dir="rtl"
          >
            <div className="flex items-start gap-3 mb-4">
              <AlertCircle className="w-6 h-6 text-amber-500 shrink-0" aria-hidden="true" />
              <div>
                <h3 className="font-bold text-foreground mb-1">حذف القالب؟</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  سيتوقف توليد الرحلات الجديدة من هذا القالب. الرحلات المنشورة
                  مسبقاً ستبقى متاحة (يمكنك حذفها يدوياً من <span className="font-medium">رحلاتي</span>).
                </p>
              </div>
            </div>
            <div className="flex gap-3">
              <Button
                variant="outline"
                className="flex-1 min-h-[44px]"
                onClick={() => setDeleteTarget(null)}
                disabled={deleteMutation.isPending}
              >
                إلغاء
              </Button>
              <Button
                onClick={() => deleteMutation.mutate(deleteTarget.id)}
                disabled={deleteMutation.isPending}
                className="flex-1 min-h-[44px] bg-destructive hover:bg-destructive/90 text-white gap-2"
              >
                {deleteMutation.isPending && <Loader2 className="w-4 h-4 animate-spin" />}
                {deleteMutation.isPending ? "جارٍ الحذف..." : "حذف القالب"}
              </Button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// ─── New template form ─────────────────────────────────────────────

function NewTemplateForm({ onCancel, onCreated }) {
  const [form, setForm] = useState({
    from_city: "",
    to_city: "",
    start_date: new Date().toISOString().slice(0, 10),
    time: "07:00",
    price: "",
    available_seats: 3,
    pattern: "weekdays",
    until_date: "",
    car_model: "",
    car_color: "",
    notes: "",
  });
  const [submitting, setSubmitting] = useState(false);

  const set = (k, v) => setForm((f) => ({ ...f, [k]: v }));

  const submit = async () => {
    // Validation
    if (!form.from_city || !form.to_city) return toast.error("اختر المدينتين");
    if (form.from_city === form.to_city) return toast.error("المدينتان يجب أن تختلفا");
    if (!form.price || Number(form.price) <= 0) return toast.error("أدخل سعراً صحيحاً");
    if (form.available_seats < 1) return toast.error("يجب أن يكون عدد المقاعد 1 على الأقل");

    setSubmitting(true);
    try {
      const { data, error } = await supabase.rpc("create_recurring_trip_template", {
        p_from_city: form.from_city,
        p_to_city: form.to_city,
        p_start_date: form.start_date,
        p_time: form.time,
        p_price: Number(form.price),
        p_available_seats: Number(form.available_seats),
        p_pattern: form.pattern,
        p_until_date: form.until_date || null,
        p_car_model: form.car_model || null,
        p_car_color: form.car_color || null,
        p_notes: form.notes || null,
      });
      if (error) throw error;
      onCreated();
    } catch (err) {
      toast.error(friendlyError(err, "تعذر إنشاء القالب"));
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="bg-card rounded-2xl border border-border p-5 mb-6">
      <h3 className="font-bold text-foreground mb-4">قالب جديد</h3>

      <div className="space-y-4">
        {/* From / To */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <div>
            <label className="text-sm font-medium mb-1 block">من</label>
            <div className="bg-muted/50 rounded-xl border border-input">
              <CityAutocomplete
                value={form.from_city}
                onChange={(v) => set("from_city", v)}
                placeholder="مدينة الانطلاق"
                iconColor="primary"
              />
            </div>
          </div>
          <div>
            <label className="text-sm font-medium mb-1 block">إلى</label>
            <div className="bg-muted/50 rounded-xl border border-input">
              <CityAutocomplete
                value={form.to_city}
                onChange={(v) => set("to_city", v)}
                placeholder="مدينة الوجهة"
                iconColor="accent"
              />
            </div>
          </div>
        </div>

        {/* Pattern picker */}
        <div>
          <label className="text-sm font-medium mb-1 block">نمط التكرار</label>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
            {Object.entries(PATTERN_LABELS).map(([key, meta]) => {
              const active = form.pattern === key;
              return (
                <button
                  key={key}
                  type="button"
                  onClick={() => set("pattern", key)}
                  className={`min-h-[60px] px-3 py-2 rounded-xl border text-right transition-colors ${
                    active
                      ? "bg-primary/10 border-primary text-primary"
                      : "bg-card border-border hover:bg-muted/50"
                  }`}
                  aria-pressed={active}
                >
                  <div className="text-sm font-medium">{meta.label}</div>
                  <div className="text-[11px] text-muted-foreground mt-0.5">{meta.hint}</div>
                </button>
              );
            })}
          </div>
        </div>

        {/* Time, price, seats */}
        <div className="grid grid-cols-3 gap-3">
          <div>
            <label className="text-sm font-medium mb-1 block">الوقت</label>
            <Input
              type="time"
              value={form.time}
              onChange={(e) => set("time", e.target.value)}
              className="min-h-[44px]"
            />
          </div>
          <div>
            <label className="text-sm font-medium mb-1 block">السعر (₪)</label>
            <Input
              type="number"
              value={form.price}
              onChange={(e) => set("price", e.target.value)}
              placeholder="20"
              className="min-h-[44px]"
            />
          </div>
          <div>
            <label className="text-sm font-medium mb-1 block">مقاعد</label>
            <Input
              type="number"
              min="1"
              max="8"
              value={form.available_seats}
              onChange={(e) => set("available_seats", e.target.value)}
              className="min-h-[44px]"
            />
          </div>
        </div>

        {/* Dates */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <div>
            <label className="text-sm font-medium mb-1 block">يبدأ من</label>
            <Input
              type="date"
              value={form.start_date}
              onChange={(e) => set("start_date", e.target.value)}
              min={new Date().toISOString().slice(0, 10)}
              className="min-h-[44px]"
            />
          </div>
          <div>
            <label className="text-sm font-medium mb-1 block">ينتهي في (اختياري)</label>
            <Input
              type="date"
              value={form.until_date}
              onChange={(e) => set("until_date", e.target.value)}
              min={form.start_date}
              className="min-h-[44px]"
            />
          </div>
        </div>

        {/* Optional car info */}
        <details className="text-sm">
          <summary className="cursor-pointer text-muted-foreground hover:text-foreground py-2">
            تفاصيل إضافية (اختياري)
          </summary>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mt-2">
            <Input
              placeholder="موديل السيارة"
              value={form.car_model}
              onChange={(e) => set("car_model", e.target.value)}
              className="min-h-[44px]"
            />
            <Input
              placeholder="اللون"
              value={form.car_color}
              onChange={(e) => set("car_color", e.target.value)}
              className="min-h-[44px]"
            />
            <Input
              placeholder="ملاحظات للركاب"
              value={form.notes}
              onChange={(e) => set("notes", e.target.value)}
              className="sm:col-span-2 min-h-[44px]"
            />
          </div>
        </details>

        {/* Submit */}
        <div className="flex gap-3 pt-2">
          <Button
            variant="outline"
            className="flex-1 min-h-[44px]"
            onClick={onCancel}
            disabled={submitting}
          >
            إلغاء
          </Button>
          <Button
            onClick={submit}
            disabled={submitting}
            className="flex-1 min-h-[44px] gap-2"
          >
            {submitting && <Loader2 className="w-4 h-4 animate-spin" />}
            {submitting ? "جارٍ الإنشاء..." : "إنشاء القالب"}
          </Button>
        </div>
      </div>
    </div>
  );
}
